### PR TITLE
UIPFI-19: Update filters & search to match ui-inventory

### PR DESCRIPTION
**Pull request by Baroquem**
https://issues.folio.org/browse/UIPFI-6
https://issues.folio.org/browse/UIPFI-18
https://issues.folio.org/browse/UIPFI-19
https://issues.folio.org/browse/UIPFI-20

Screen Shot 2021-03-11 at 4 59 56 PM

This PR references the four interrelated stories listed above, all of which involve updating the search and filter pane to match the options presented in ui-inventory. The major challenge turned out to be adapting the inventory filter code, which presumes the use of `<SearchAndSort>`, to make use of the plugin's `searchAndSortQuery` function.

To avoid large swathes of redundant code, the approach taken here is to identify common files that can be refactored out of both repositories (this and ui-inventory) into a shared component repo, as has been done with things like stripes-erm-components. In this draft version, there is a new, top-level `Imports` directory. This, confusingly, contains an `imports` subdirectory that holds the reusable files to be extracted to a common repo (this will eventually be removed from the plugin repo). The `FilterRenderers` subdirectory contains imported but modified code that can't be easily extracted, unfortunately; but it's probably worth keeping it labeled as `Imports` to indicate its origin.

---

As things have turned out, many of the files I'd hoped to extract and use in common for ui-inventory and the plugin had to be modified to adapt them to the plugin and thus can't be easily shared. I think we may have to create a new issue to address the shared repository concept, which will involve some fairly delicate refactoring of ui-inventory.

### CODE REVIEW

**Comment by Dmitriy-Litvinenko** [comment]
@Baroquem Hello, thank you. I see that story https://issues.folio.org/browse/UIPFI-20 have status "IN PROGRESS". Could you please clarify we can start review or we need wait until current story will be moved to "IN CODE REVIEW" (something will be changed in current pull request)?

**Review by mkuklis — APPROVED** [review]
Wow lots of work here @Baroquem! Nice job. I'm sure you will be happy to merge this one in :)

**Review by Dmitriy-Litvinenko — CHANGES_REQUESTED** [review]
In review

**Comment by Dmitriy-Litvinenko** [comment]
@Baroquem Thank you, nice job.
How i understood this plugin used in several modules (ui-inventory, ui-receiving and ui-receiving).
Many paths added to manifest (Imports/imports/DataProvider.js).
1. Could you please double check should we add changes in okapiInterfaces?
2. What permission should have user for use current plagin in ui-inventory, ui-receiving and ui-receiving (BE can return error "<permiton name> permission is required" when we use api call)?
3. Should we add bigtest or jest test?
...
CC: @zburke @mkuklis

**Pull request merged**
